# Generated by Django 2.1.1 on 2018-09-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile-pics/default.jpg', upload_to='profile-pics'),
        ),
    ]
