# Generated by Django 2.1.1 on 2018-10-13 04:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='objective',
            field=tinymce.models.HTMLField(),
        ),
    ]
