# Generated by Django 2.1.1 on 2018-10-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181011_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
