# Generated by Django 2.1.1 on 2018-09-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180921_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile-pics/default.jpg/', upload_to='profile-pics'),
        ),
    ]
