# Generated by Django 2.1.1 on 2018-10-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20181011_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
