# Generated by Django 2.1.1 on 2018-11-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_auto_20181103_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='competency',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 'Beginner Level'), (2, 'Conversational Level'), (3, 'Business Level'), (4, 'Fluent Level')], null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='competency',
            field=models.IntegerField(blank=True, choices=[('', '-----'), (1, 'Below Average'), (2, 'Average'), (3, 'Good'), (4, 'Excellent')], null=True),
        ),
    ]
