# Generated by Django 2.1.1 on 2018-10-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
