# Generated by Django 2.1.1 on 2018-10-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_certification_education_language_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.FloatField(blank=True),
        ),
    ]
